image = "/users/<YOUR_USERNAME>/scratch/finetune/slurm/vllm.sqsh"
mounts = [
    "/capstor",
    "/iopsstor",
    "/users",
]

[annotations]
com.hooks.aws_ofi_nccl.enabled = "true"
com.hooks.aws_ofi_nccl.variant = "cuda12"

