defaults:
  - model: mamba2.8
  - optim: adamw
  - scheduler: cosine
  - data: the_pile
  - loss: default
  - trainer: default
  - dataloader
  - _self_

seed: 42

model_dir: models

run_id: ${oc.env:SLURM_JOB_NAME}_${oc.env:MODEL_SIZE}_${oc.env:CRITERION}_w${oc.env:LAMBDA}_${oc.env:SLURM_JOB_ID}
# push_to_hub: false
# hub_repo_id: mamba-constrict-${oc.env:MODEL_SIZE}-${oc.env:CRITERION}-w${oc.env:LAMBDA}

wandb:
  project: finetune-mamba
  entity: mamba-monks
  name: ${run_id}

hydra:
  run:
    dir: outputs/${run_id}
  sweep:
    dir: outputs/${run_id}
