defaults:
  - model: mamba2.8
  - optim: adamw
  - data: the_pile
  - loss: default
  - trainer
  - _self_

seed: 42
checkpoint_every_n_epochs: 10

wandb:
  project: finetune-mamba

hydra:
  run:
    dir: outputs/${oc.env:SLURM_JOB_NAME}_${oc.env:SLURM_JOB_ID}
  sweep:
    dir: outputs/${oc.env:SLURM_JOB_NAME}_${oc.env:SLURM_JOB_ID}
