defaults:
  - model: mamba2.8
  - optim: adamw
  - scheduler: cosine
  - data: the_pile
  - loss: default
  - dataloader
  - trainer
  - _self_

seed: 42
checkpoint_every_n_epochs: 10

model_dir: models

wandb:
  project: finetune-mamba
  entity: mamba-monks

hydra:
  run:
    dir: outputs/${oc.env:SLURM_JOB_NAME}_${oc.env:SLURM_JOB_ID}
  sweep:
    dir: outputs/${oc.env:SLURM_JOB_NAME}_${oc.env:SLURM_JOB_ID}
