# @package trainer
deterministic: true
accelerator: auto
gradient_clip_val: 1.0
enable_model_summary: true

enable_progress_bar: true
log_every_n_steps: 10
precision: bf16-mixed
accumulate_grad_batches: 4

max_steps: 100

val_check_interval: 100 # Validate every 100 training steps
limit_val_batches: 0.01  # Use 1% of validation set
