# @package trainer
deterministic: true
accelerator: auto
gradient_clip_val: 1.0
enable_model_summary: true


enable_progress_bar: false
log_every_n_steps: 10
precision: bf16-mixed
accumulate_grad_batches: 4

max_steps: 100

# val_check_interval: 200 # Validate every 200 training steps
# check_val_every_n_epochs: None